Players in Tours
ykostov/tennis.phx pull request #7
Opened 2021-04-04 10:27 UTC by ykostov

2021-04-04 10:27 UTC, ykostov commented
WIP

2021-04-05 06:07 UTC, rmilushev requested changes

2021-04-05 06:07 UTC, rmilushev commented on lib/tennis_web/live/gladiator_live.ex
> +    gladiator = Home.get_gladiator!(params["id"])
Please, check if we have a `Home` module.

2021-04-05 11:44 UTC, ykostov commented on lib/tennis_web/live/gladiator_live.ex
> +    gladiator = Home.get_gladiator!(params["id"])
Its `Tours`, fixed :)

2021-04-05 14:01 UTC, rmilushev requested changes

2021-04-05 14:01 UTC, rmilushev commented on lib/tennis_web/templates/gladiator/show.html.eex
> +<main class="profile-page">
Imo this tamplate have to be `live` => `.leex`

2021-04-05 16:25 UTC, ykostov commented
Resolved :+1:

2021-04-06 20:12 UTC, rmilushev requested changes

2021-04-06 20:12 UTC, rmilushev commented on lib/tennis_web/templates/gladiator/index.html.eex
> +            <td class="px-4 py-3"><%= link gladiator.title , to: Routes.gladiator_path(@conn, :show, gladiator) %></td>
We need a link to `live` path [here](https://github.com/N-Patarov/bgsite_official/blob/main/lib/bgsite_official_web/templates/websites/index.html.eex#L19), I see you have missed to add `live` path on your router too. Check here: [example live path](https://github.com/N-Patarov/bgsite_official/blob/enroll_many_to_many/lib/bgsite_official_web/router.ex#L70).

2021-04-08 20:03 UTC, rmilushev requested changes

2021-04-08 20:03 UTC, rmilushev commented on lib/tennis_web/live/gladiator_live.ex
> +
Please, add `alias Tennis.Tours` to be able to use functions from `Tennis.Tours` module without `Tennis.` prefix. Now the module is not found.
Second option: on row 15: 
```gladiator = Tennis.Tours.get_gladiator!(params["id"])```

2021-04-10 20:41 UTC, merged